name: 'Codeception Tests'
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        suite:
          # - acceptance
          - aggregatorv1
          # - blocks_editor_integration
          # - features
          - integration
          - muintegration
          - restv1
          - views_integration
          - views_rest
          - views_settings
          - views_ui
          - views_wpunit
          - wpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          submodules: recursive
      - name: Checkout automation tools
        uses: actions/checkout@v1
        with:
          repository: moderntribe/tric
          ref: fix/ci-message-not-a-tty
          path: tric
          fetch-depth: 1
      - name: Add tric to the PATH
        run: echo "::set-env name=PATH::${GITHUB_WORKSPACE}/../tric:$PATH"
      - name: Set run_context() for tric
        run: echo "::set-env name=TRIC::1"
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "::set-env name=SSH_AUTH_SOCK::/tmp/ssh_agent.sock"
      - name: Set up tric for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          tric here
          tric interactive off
          tric build-prompt off
          tric build-subdir off
          tric xdebug off
          tric debug on
          tric info
      - name: Print the current tric configuration
        run: tric config
      - name: Set up Common
        run: |
          tric use the-events-calendar/common
          tric composer install --no-dev
      - name: Set up The Events Calendar
        run: |
          tric use the-events-calendar
          tric composer install
      - name: Print tric info
        run: tric info
      - name: Run suite tests
        run: tric run ${{ matrix.suite }}
